name: install

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  simple_deployment_pipeline:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: npm install 
      run: npm install  
    - name: lint
      run: stall eslint eslint-plugin-react --save-dev && npm run eslint
